import crypto from 'crypto';
export const Users = [
    {
        firstName: 'Cuong',
        lastName: 'Nguyen Quoc',
        email: 'cuongnq@tdmu.edu.vn',
        password:crypto.createHash('md5').update('1').digest('hex'),
        department: 'Thu Dau Mot University',
        position: 'Principal',
        image: '',
        role:'client',
    },
    {
        
        firstName: 'Quang',
        lastName: 'Nguyen Ho',
        email: 'quangnh@tdmu.edu.vn',
        password:crypto.createHash('md5').update('1').digest('hex'),
        department: 'Institute of Engineering and Technology',
        position: 'Director',
        image: '',
        role:'client',
    },
    {
        firstName: 'Quynh',
        lastName: 'Trinh Nhu',
        email: 'quynhtn@tdmu.edu.vn',
        password:crypto.createHash('md5').update('1').digest('hex'),
        department: 'Institute of Engineering and Technology',
        position: 'Secretary',
        image: '',
        role:'client',
    },
    {
        firstName: 'Vinh',
        lastName: 'Nguyen Huu',
        email: 'vinhnh@tdmu.edu.vn',
        password:crypto.createHash('md5').update('1').digest('hex'),
        department: 'Institute of Engineering and Technology',
        position: 'Lecturer',
        image: '',
        role:'client',
    },
    {
        firstName: 'Huu',
        lastName: 'Tran Van',
        email: 'huutv@tdmu.edu.vn',
        password:crypto.createHash('md5').update('1').digest('hex'),
        department: 'Institute of Engineering and Technology',
        position: 'Lecturer',
        image: '',
        role:'client',
    },
];
export const Courses =[
    {
        courseID:"LING105",
        courseName:"Kỹ thuật lập trình (2+1)",
        totalCredits:3, 
    },
    {
        courseID:"LING196",
        courseName:"Phương pháp lập trình hướng đối tượng (3+1)",
        totalCredits:4, 
    },
    {
        courseID:"TI235",
        courseName:"Báo Cáo Tốt Nghiệp (0+10)",
        totalCredits:10, 
    },
];
export const Students =[
    {
        studentID:"2024801030090", 
        fullName:"Nguyen Trong Tuan Anh", 
        dateOfBirth:"", 
        gender:"male", 
        phone:"0975824272", 
        email:"2024801030090@student.tdmu.edu.vn" , 
        status:"studying" , 
        className:"D20KTPM02", 
        department:"Institute of Engineering and Technology", 
        majors:"Software technology", 
        shoolYear: 4, 
        totalCredits:150,
        accumulatedCredits:0, 
        idNumber:"", 
        dateOfIssue:"", 
        placeOfIssue:"", 
        image:"",
    },
    {
        studentID:"2124802010493", 
        fullName:"Huỳnh Tấn Anh", 
        dateOfBirth:"", 
        gender:"male", 
        phone:"	0961541437", 
        email:"2124802010493@student.tdmu.edu.vn" , 
        status:"studying" , 
        className:"D21CNTT06", 
        department:"Institute of Engineering and Technology", 
        majors:"Software technology", 
        shoolYear: 4, 
        totalCredits:150,
        accumulatedCredits:0, 
        idNumber:"", 
        dateOfIssue:"", 
        placeOfIssue:"", 
        image:"",
    },
    {
        studentID:"2124801030241", 
        fullName:"Cao Hữu Cường", 
        dateOfBirth:"", 
        gender:"male", 
        phone:"	0344567795", 
        email:"2124801030241@student.tdmu.edu.vn" , 
        status:"studying" , 
        className:"D21KTPM01", 
        department:"Institute of Engineering and Technology", 
        majors:"Software technology", 
        shoolYear: 4, 
        totalCredits:150,
        accumulatedCredits:0, 
        idNumber:"", 
        dateOfIssue:"", 
        placeOfIssue:"", 
        image:"",
    },
];
